### ISSUE TITLE
Wishlist for API/API Design/documentation?

### ISSUE THREAD

**Issue by maqifrnswa** [xeroc/python-graphenelib#24]
Hi xeroc,

# API Wishlist?
just curious what your wishlist for the client/WS API is - perhaps I can add them to the witness_node or cli_wallet.

# Library Architecture?
Also, related - what do you envision as the overall architecture of the library, in the end? Would you want to create an even higher level abstraction of the current API?

# Documentation?
It could be good to document how the library interacts with everything. This is my understanding so far:
1) the api class can connect to cli_wallet and implements all RPC commands
2) the ws api class is a subclass of api, connects to witness_node via authenticated ws and also via unauthenticated RPC commands
3) the wsprotocol implements asynchronous message handling.

### awesome features:
1) the wsprotocol has a class attribute of objectMap, which is a dictionary of every object you have looked in to - and it is updated every block as needed! Word of caution: orders (1.7.*) are deleted from the blockchain when they are filled, but they are not deleted from the objectMap as no notification is ever sent by witness_node when they are deleted! (https://github.com/cryptonomex/graphene/issues/488) Also, when you use getObject or getObjectcb, the library checks objectMap first - saving extra calls!

### Some things I learned:
1) objectMap is shared among all instances of the wsprotocol class, so even though the ws api only stores the class (not the instance), it will have access to objectMap. Instances are generated by autobahn's websocket factory.
2) the self.api_ids is not shared among all instances of the wsprotocol class. This causes problems if you try to connect to a restricted API in anything except a subclass of your wsprotocol
3) That said, you can "trick" python into giving you the actual instance of the protocol if you set a callback to function in another class. This causes both your new class and the protocol to be passed as the first and second arguments to the method in the new class, thus giving you access to self.api_ids

### A complex use case
I need something with both cli_wallet and witness_node interface, and I want to get the actual protocol passed back to me. I can do something like this:
1) Create a new class 
```
class MarketBalanceBot :
    def __init__(self, wsapi, walletapi) :
        self.wsapi=wsapi
        self.walletapi=walletapi
        self.walletapi.unlock(config.password)
            ## Set Callbacks for object changes
        self.wsapi.setObjectCallbacks({"2.1.0" : self.oneNewBlock})
    def onNewBlock(self,proto,data):
        print("I'm doing this just once, as I have the real protocol!")
        proto.database_callbacks_ids.pop("2.1.0")
        print("How I can see the api ids with the real protocol:")
        print(proto.api_ids)
        print("But my wsapi class doesn't know the api ids!")
        try:
            print(self.wsapi.proto.api_ids)
        except:
            print("error:", sys.exc_info()[0])

if __name__ == '__main__':
    wsapi      = GrapheneWebsocket(config.IP,config.WSPORT,"","", GrapheneWebsocketProtocol)
    clientrpc=GrapheneAPI(config.IP,config.WALLETPORT,"","")
    bot=MarketBalanceBot(wsapi,clientrpc)
    wsapi.connect()
    wsapi.connect().run_forever()
```
That means we don't have to make our own subclass of GrapheneWebsocketProtocol, instead make GrapheneWebsocketProtocol cannonical for all users, and have them just make classes that have the APIs as attributes of the class

**Comment by xeroc** [comment]
> API Wishlist?
> 
> just curious what your wishlist for the client/WS API is - perhaps I can add them to the witness_node or cli_wallet.

There is an API wishlist: https://github.com/cryptonomex/graphene/issues/382
Essentially, I would like to provide a simple library that offers the same calls as poloniex .. so that people can simply plug&play their poloniex-capable bots into bitshares



> Library Architecture?
> 
> Also, related - what do you envision as the overall architecture of the library, in the end? Would you want to create an even higher level abstraction of the current API?

I usually keep things close together: `*base` is the core functionalities of bitshares like address, pubkey, wif key stuff and later transaction signing. `*api` is obviously a folder for  api related stuff and `*extra` would be for libraries that abstract things away from the end user .. like proposed transfers, or maybe 3rd party 'plugins' .. But in the end, this is a growing project and so can the requirements and the organization.




> Documentation?
> 
> It could be good to document how the library interacts with everything. This is my understanding so far:
> 1) the api class can connect to cli_wallet and implements all RPC commands

yes

> 2) the ws api class is a subclass of api, connects to witness_node via authenticated ws and also via unauthenticated RPC commands

yes, though there is an issue I identified earlier last week.
The idea was to have an API for the cli_wallet (RPC) and one for the witness_node (websocket). However the witness node can also answer RPC requests (though has a different set of available calls). That's why the RPC class is a base class and the websocket class a child class.
However, if I connect to a websocket server using a URL like bitshares.openledger.info/ws (which is proxied to the 'real' API), the RPC part of the websocket connection will not work properly. Haven't figured out a way to fix this yet, not sure it can even be fixed "nicely". Do you have a recommendation how to separated RPC and Websockets properly?



> 3) the wsprotocol implements asynchronous message handling.



> awesome features:
> 
> 1) the wsprotocol has a class attribute of objectMap, which is a dictionary of every object you have looked in to - and it is updated every block as needed! Word of caution: orders (1.7.*) are deleted from the blockchain when they are filled, but they are not deleted from the objectMap as no notification is ever sent by witness_node when they are deleted! (cryptonomex/graphene#488) Also, when you use getObject or getObjectcb, the library checks objectMap first - saving extra calls!

Thanks for highlighting the issue with 1.7.*. Haven't looked into it yet.
I think we can easily force the library to poll those 1.7.* objects if they are used. The whole getObject idea is not yet implemented to my satisfaction yet either. It's on the list of things to improve




> Some things I learned:
> 
> 1) objectMap is shared among all instances of the wsprotocol class, so even though the ws api only stores the class (not the instance), it will have access to objectMap. Instances are generated by autobahn's websocket factory.

Yes. That was the intension. Though I have never really looked into the side effects of having several instances running

> 2) the self.api_ids is not shared among all instances of the wsprotocol class. This causes problems if you try to connect to a restricted API in anything except a subclass of your wsprotocol

Good point. If you add it to 
https://github.com/xeroc/python-graphenelib/blob/master/grapheneapi/graphenewsprotocol.py#L15-L21
It will be shared as well.

> 3) That said, you can "trick" python into giving you the actual instance of the protocol if you set a callback to function in another class. This causes both your new class and the protocol to be passed as the first and second arguments to the method in the new class, thus giving you access to self.api_ids

You can share variables across instances by using 'static' variables
http://stackoverflow.com/questions/68645/static-class-variables-in-python

You simply have to define the variable right after `class ClassName():`




> A complex use case
> 
> I need something with both cli_wallet and witness_node interface, and I want to get the actual protocol passed back to me. I can do something like this:
> 1) Create a new class
> That means we don't have to make our own subclass of GrapheneWebsocketProtocol, instead make GrapheneWebsocketProtocol cannonical for all users, and have them just make classes that have the APIs as attributes of the class

This would be another abstraction layer and I think I can write a new `GrapheneWebsocketProtocol` that does exactly this with a template for the `botClass` and it's sub routines.

**Comment by xeroc** [comment]
Hope the abstraction class here solves your issues:
https://github.com/xeroc/python-graphenelib/blob/master/grapheneexchange/exchange.py
